on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  cdk:
    name: CDK
    runs-on: ubuntu-latest
    timeout-minutes: 60
    environment: ${{ inputs.environment }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/DeploymentRole-${{ inputs.environment }}
      - name: Login to registry
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/Hydrogen
          cache: npm
      - name: Deploy AWS CDK
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          ORGANIZATION: ${{ vars.ORGANIZATION }}
          SUBSCRIBER: ${{ vars.SUBSCRIBER }}
        run: |
          npm ci
          npm run cdk deploy -- --all --require-approval never
