on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yaml
    with:
      environment: prod
    secrets: inherit
  deploy:
    needs: test
    name: Deploy
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: prod
    secrets: inherit
