name: Push on tags

on:
  push:
    tags:
      - "*"

jobs:
  # Sandbox environment
  test-sandbox:
    name: Test sandbox
    uses: ./.github/workflows/test.yaml
    with:
      environment: sandbox
    secrets: inherit
  deploy-sandbox:
    needs: test-sandbox
    name: Deploy sandbox
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: sandbox
    secrets: inherit

  # Production environment
  test-prod:
    needs: deploy-sandbox
    name: Test production
    uses: ./.github/workflows/test.yaml
    with:
      environment: prod
    secrets: inherit
  deploy-prod:
    needs: test-prod
    name: Deploy production
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: prod
    secrets: inherit
